name: Testing
on: push
jobs:
  testing:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Installing golang ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: make test
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28.3
